spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: rootuser

#JPA Settings
  jpa.hibernate.ddl_auto: create